// frontend_react/src/components/Question.jsx
import './../style/Question.css'
import Answer from './Answer'

export default function Question({question,name,saveSelectedAnswer,color,indexStyle}){

    return(
        <div className="question" style={{
               borderImage: color[indexStyle],
            }}>
            <div className="header">
            <p className="text">{question.text}</p>
            <p className="points">Points: {question.points}</p>
        </div>
        <div className="answers">
            {
                question.answers.map((answer,index)=>{
                    return <Answer answer={answer} key={answer.id} name={name} saveSelectedAnswer={saveSelectedAnswer}></Answer>
                })
            }
        </div>
</div>
    )
}

// frontend/src/components/Question.vue
<script setup>
import Answer from './Answer.vue';

const props = defineProps(['question', 'index'])

</script>

<template>
    <div class="header">
        <p class="text">{{ props.question.text }}</p>
        <p class="points">Points: {{ props.question.points }}</p>
        <Answer class="answer" v-for="(answer, i) in props.question.answers" :key="i" :index="i" :answer="answer">
        </Answer>
    </div>
</template>

<style></style>
